spring:
  application:
    name: currency-exchange
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
server:
  port: 8000
management:
  tracing:
    sampling:
      probability: 1
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
logging:
  pattern:
    level: "%5p [${spring.application.name},%X{traceId:-},%X{spanId:-}]"